---
# handlers file for containerd
- name: Start containerd service
  ansible.builtin.systemd:
    name: "{{ containerd_service_name }}"
    state: started
    enabled: true
    daemon_reload: true
  listen: start containerd

- name: Restart containerd service
  ansible.builtin.systemd:
    name: "{{ containerd_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true
  listen: restart containerd

- name: Stop containerd service
  ansible.builtin.systemd:
    name: "{{ containerd_service_name }}"
    state: stopped
    enabled: false
    daemon_reload: true
  listen: stop containerd